cnccv_house:
    resource: "@CnccvHouseBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

logout:
    path: /logout

#Exemple de route
#Le projet:
#    path: le nom de la route
#    defaults: {_controller: LeBundle:LeController:NomDeLaction}

#Dispo
dispo:
    path: /
    defaults: {_controller: CnccvHouseBundle:Default:dispoLogement}

#PageDemarrage
page:
    path: /
    defaults: {_controller: CnccvHouseBundle:Default:pageDemarrage}

#PrixLogement
prix:
    path: /
    defaults: {_controller: CnccvHouseBundle:Default:prixLogement}

#Cards
cards:
    path: /
    defaults: {_controller: CnccvHouseBundle:Card:index}

description_show:
    path: /description/{id}
    defaults: {_controller: CNccvHouseBundle:Card:show}

#Admin
admin:
    path:      /admin
    defaults: {_controller: CnccvHouseBundle:Admin:index}

#Qui sommes-nous
qui:
    path:      /qui
    defaults: {_controller: CnccvHouseBundle:Qui:index}

#User
user_index:
    path: admin/user
    defaults: {_controller: CnccvHouseBundle:User:index}

user_new:
    path: admin/user/new
    defaults: {_controller: CnccvHouseBundle:User:new}

user_show:
    path: admin/user/{id}
    defaults: {_controller: CnccvHouseBundle:User:show}

user_edit:
    path: admin/user/edit/{id}
    defaults: {_controller: CnccvHouseBundle:User:edit}

user_delete:
    path: admin/user/delete/{id}
    defaults: {_controller: CnccvHouseBundle:User:delete}

#Evenement
evenement_index:
    path: admin/evenement
    defaults: {_controller: CnccvHouseBundle:Evenement:index}

evenement_new:
    path: admin/evenement/new
    defaults: {_controller: CnccvHouseBundle:Evenement:new}

evenement_show:
    path: admin/evenement/show/{id}
    defaults: {_controller: CnccvHouseBundle:Evenement:show}

evenement_edit:
    path: admin/evenement/edit/{id}
    defaults: {_controller: CnccvHouseBundle:Evenement:edit}

evenement_delete:
    path: admin/evenement/delete/{id}
    defaults: {_controller: CnccvHouseBundle:Evenement:delete}

#Logement
logement_index:
    path: admin/logement
    defaults: {_controller: CnccvHouseBundle:Logement:index}

logement_new:
    path: admin/logement/new
    defaults: {_controller: CnccvHouseBundle:Logement:new}

logement_show:
    path: admin/logement/show/{id}
    defaults: {_controller: CnccvHouseBundle:Logement:show}

logement_edit:
    path: admin/logement/edit/{id}
    defaults: {_controller: CnccvHouseBundle:Logement:edit}

logement_delete:
    path: admin/logement/delete/{id}
    defaults: {_controller: CnccvHouseBundle:Logement:delete}

#Note
note_index:
    path: admin/note
    defaults: {_controller: CnccvHouseBundle:Note:index}

note_new:
    path: admin/note/new
    defaults: {_controller: CnccvHouseBundle:Note:new}

note_show:
    path: admin/note/show/{id}
    defaults: {_controller: CnccvHouseBundle:Note:show}

note_edit:
    path: admin/note/edit/{id}
    defaults: {_controller: CnccvHouseBundle:Note:edit}

note_delete:
    path: admin/note/delete/{id}
    defaults: {_controller: CnccvHouseBundle:Note:delete}

#Parametres_prix
parametres_prix_index:
    path: admin/parametres_prix
    defaults: {_controller: CnccvHouseBundle:Parametres_prix:index}

parametres_prix_new:
    path: admin/parametres_prix/new
    defaults: {_controller: CnccvHouseBundle:Parametres_prix:new}

parametres_prix_show:
    path: admin/parametres_prix/show/{id}
    defaults: {_controller: CnccvHouseBundle:Parametres_prix:show}

parametres_prix_edit:
    path: admin/parametres_prix/edit/{id}
    defaults: {_controller: CnccvHouseBundle:Parametres_prix:edit}

parametres_prix_delete:
    path: admin/parametres_prix/delete/{id}
    defaults: {_controller: CnccvHouseBundle:Parametres_prix:delete}

#Reservation
reservation_index:
    path: admin/reservation
    defaults: {_controller: CnccvHouseBundle:Booking:index}

reservation_new:
    path: admin/reservation/new
    defaults: {_controller: CnccvHouseBundle:Booking:new}

reservation_show:
    path: admin/reservation/show/{id}
    defaults: {_controller: CnccvHouseBundle:Booking:show}

reservation_edit:
    path: admin/reservation/edit/{id}
    defaults: {_controller: CnccvHouseBundle:Booking:edit}

reservation_delete:
    path: admin/reservation/delete/{id}
    defaults: {_controller: CnccvHouseBundle:Booking:delete}

