# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.form.registration:
        class: Cnccv\HouseBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }