<?php

namespace Cnccv\HouseBundle\Repository;

/**
 * Base_prixRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Base_prixRepository extends \Doctrine\ORM\EntityRepository
{
}
