<?php

namespace Cnccv\HouseBundle\Repository;

/**
 * logementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class logementRepository extends \Doctrine\ORM\EntityRepository
{
}
