<?php

namespace Cnccv\HouseBundle\Repository;

/**
 * noteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class noteRepository extends \Doctrine\ORM\EntityRepository
{
}
