<?php

namespace Cnccv\HouseBundle\Repository;

/**
 * Parametres_prixRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Parametres_prixRepository extends \Doctrine\ORM\EntityRepository
{
}
